DROP DATABASE IF EXISTS PB_LEM;

CREATE DATABASE PB_LEM;

USE PB_LEM;

-- Create MEMBER table
CREATE TABLE MEMBER (
    MEMBER_ID INT AUTO_INCREMENT PRIMARY KEY,
    MEMBER_NAME VARCHAR(50) NOT NULL,
    MEMBER_TYPE VARCHAR(50) NOT NULL
);

-- Create LEM_DATA table
CREATE TABLE LEM_DATA (
    LEMDATA_ID INT AUTO_INCREMENT PRIMARY KEY,
    MEMBER_ID INT NOT NULL,
    UTC_T TIMESTAMP NOT NULL,
    ELECTRICITY_LOAD FLOAT,
    RESIDENTIAL_ELECTRICITY_PRICE FLOAT,
    RESIDENTIAL_SOLAR_GENERATION FLOAT,
    RESIDENTIAL_WIND_GENERATION FLOAT,
    TEMPERATURE FLOAT,
    RELATIVE_HUMIDITY FLOAT,

    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID)
);

-- Create PRICING_DATA table
CREATE TABLE PRICING_DATA (
    PRICING_DATA_ID INT AUTO_INCREMENT PRIMARY KEY,
    PROSUMERS_COMMUNITY_PRICE FLOAT,
    TRADING_COMPANY_SMALL_PRICE FLOAT
);

-- Create LEM_RESULTS table
CREATE TABLE LEM_RESULTS (
    RESULTS_ID INT AUTO_INCREMENT PRIMARY KEY,
    UTC_T TIMESTAMP NOT NULL,
    LEM_TOTAL_PRODUCED FLOAT,
    LEM_TOTAL_CONSUMED FLOAT
);

-- Create LEM_BILLING table
CREATE TABLE LEM_BILLING (
    BILLING_ID INT AUTO_INCREMENT PRIMARY KEY,
    RESULTS_ID INT NOT NULL,
    MEMBER_ID INT NOT NULL,
    BILL FLOAT,

    FOREIGN KEY (RESULTS_ID) REFERENCES LEM_RESULTS(RESULTS_ID),
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID)
);

-- Insert sample members
INSERT INTO MEMBER (MEMBER_NAME, MEMBER_TYPE) VALUES ("Householder0", "Prosumer");
INSERT INTO MEMBER (MEMBER_NAME, MEMBER_TYPE) VALUES ("Householder1", "Prosumer");
INSERT INTO MEMBER (MEMBER_NAME, MEMBER_TYPE) VALUES ("Householder2", "Prosumer");
INSERT INTO MEMBER (MEMBER_NAME, MEMBER_TYPE) VALUES ("Householder3", "Consumer");
INSERT INTO MEMBER (MEMBER_NAME, MEMBER_TYPE) VALUES ("Householder4", "Consumer");
INSERT INTO MEMBER (MEMBER_NAME, MEMBER_TYPE) VALUES ("Householder5", "Consumer");
INSERT INTO MEMBER (MEMBER_NAME, MEMBER_TYPE) VALUES ("Householder6", "Prosumer");
INSERT INTO MEMBER (MEMBER_NAME, MEMBER_TYPE) VALUES ("Householder7", "Prosumer");
INSERT INTO MEMBER (MEMBER_NAME, MEMBER_TYPE) VALUES ("Householder8", "Prosumer");
INSERT INTO MEMBER (MEMBER_NAME, MEMBER_TYPE) VALUES ("Householder9", "Prosumer");
INSERT INTO MEMBER (MEMBER_NAME, MEMBER_TYPE) VALUES ("TradingCompany", "TradingCompany");

-- Insert pricing data
INSERT INTO PRICING_DATA (PROSUMERS_COMMUNITY_PRICE, TRADING_COMPANY_SMALL_PRICE) VALUES (0.16, 0.24);
