DROP DATABASE IF EXISTS WEATHER_RES;

CREATE DATABASE WEATHER_RES;

USE WEATHER_RES;

-- Create WEATHER_RESULTS table
CREATE TABLE WEATHER_RESULTS (
    WEATHERRES_ID INT AUTO_INCREMENT PRIMARY KEY,
    TEMPERATURE FLOAT NOT NULL,
    RELATIVE_HUMIDITY FLOAT NOT NULL
);